# Generated by Django 3.2 on 2025-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('feed_type', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('feed_brand', models.CharField(max_length=200)),
                ('quantity_kg', models.CharField(max_length=100)),
                ('cost_per_kg', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('total_cost', models.CharField(max_length=100)),
            ],
        ),
    ]
