# Generated by Django 3.2 on 2025-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='cost_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
