# Generated by Django 3.2 on 2025-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=200)),
                ('flock', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('paid_by', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
