# Generated by Django 3.2 on 2025-11-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuresales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bags', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('price_per_bag', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
