# Generated by Django 3.2 on 2025-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuresales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuresales',
            name='price_per_bag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='manuresales',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
