# Generated by Django 3.2 on 2025-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuresales', '0002_manuresales_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuresales',
            name='manure_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manuresales',
            name='manure_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
