# Generated by Django 3.2 on 2025-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggsales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsales',
            name='price_per_tray',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eggsales',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
