# Generated by Django 3.2 on 2025-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flocksetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poultry_house', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('initial_quantity', models.CharField(max_length=200)),
                ('age_in_days_at_arrival', models.CharField(max_length=100)),
                ('source_supplier', models.CharField(max_length=100)),
                ('cost_per_bird', models.CharField(max_length=100)),
            ],
        ),
    ]
