# Generated by Django 3.2 on 2025-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocksetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flocksetup',
            name='initial_quantity',
            field=models.IntegerField(),
        ),
    ]
