# Generated by Django 3.2 on 2025-11-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocksetup', '0002_alter_flocksetup_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flocksetup',
            name='cost_per_bird',
            field=models.IntegerField(),
        ),
    ]
