# Generated by Django 3.2 on 2025-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocksetup', '0003_alter_flocksetup_cost_per_bird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flocksetup',
            name='cost_per_bird',
            field=models.FloatField(),
        ),
    ]
