# Generated by Django 3.2 on 2025-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('treatment_type', models.CharField(max_length=200)),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage_per_liter', models.IntegerField()),
                ('total_quantity_used', models.IntegerField()),
                ('administered_by', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
