# Generated by Django 3.2 on 2025-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='drug_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
