# Generated by Django 3.2 on 2025-11-30 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meatsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('kgs_sold', models.IntegerField()),
                ('price_per_kg', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meatsales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
