# Generated by Django 3.2 on 2025-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatsales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatsales',
            name='chicken_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meatsales',
            name='processing_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
