# Generated by Django 3.2 on 2025-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.CharField(max_length=200)),
                ('movement_type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
