# Generated by Django 3.2 on 2025-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_movement', '0002_inventory_movement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_movement',
            name='movement_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
