# Generated by Django 3.2 on 2025-12-03 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currentstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressed', models.IntegerField()),
                ('undressed', models.IntegerField()),
                ('chicken_parts', models.IntegerField()),
                ('manure_bags', models.IntegerField()),
                ('chicken_packaging_type', models.CharField(max_length=100)),
                ('manure_packaging_type', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
