# Generated by Django 3.2 on 2025-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='chicken_feed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
