# Generated by Django 3.2 on 2025-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_stock', '0002_currentstock_chicken_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='vaccines',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
