# Generated by Django 3.2 on 2025-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggsales', '0002_eggsales_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsales',
            name='egg_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eggsales',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eggsales',
            name='sale_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
