# Generated by Django 3.2 on 2025-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('unit_price', models.CharField(max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('source_supplier', models.CharField(max_length=100)),
                ('last_restock_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
