# Generated by Django 3.2 on 2025-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
