# Generated by Django 3.2 on 2025-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20251124_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
