# Generated by Django 3.2 on 2025-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity_sold', models.CharField(max_length=200)),
                ('weight_per_bird_kg', models.CharField(max_length=100)),
                ('price_per_bird', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
