# Generated by Django 3.2 on 2025-11-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culling',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culling', to=settings.AUTH_USER_MODEL),
        ),
    ]
