# Generated by Django 3.2 on 2025-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culling',
            name='price_per_bird',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='culling',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='culling',
            name='weight_per_bird_kg',
            field=models.IntegerField(),
        ),
    ]
