# Generated by Django 3.2 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0002_auto_20251124_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culling',
            name='price_per_bird',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='culling',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
