# Generated by Django 3.2 on 2025-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eggproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('eggs_collected', models.IntegerField()),
                ('cracked_eggs', models.CharField(max_length=200)),
                ('broken_eggs', models.CharField(max_length=200)),
                ('total_egg_weight_kg', models.IntegerField()),
                ('collector_name', models.CharField(max_length=100)),
            ],
        ),
    ]
