# Generated by Django 3.2 on 2025-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meatproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_size', models.IntegerField()),
                ('average_weight_kg', models.IntegerField()),
                ('lowest_weight_kg', models.IntegerField()),
                ('highest_weight_kg', models.IntegerField()),
            ],
        ),
    ]
